### ISSUE TITLE
Couldn't read data for number <multi-account>: EOF. Is the number properly registered?

### ISSUE THREAD

**Issue by Skons** [bbernhard/signal-cli-rest-api#721]
### The problem

It seems that after updating to 0.93.0 i get the error described in the title of this issue.. The jsonrpc2.yml is configured like this
``` yaml
config:
  <multi-account>:
    tcp_port: 6001
    fifo_pathname: /tmp/sigsocket1
```

I also do not have a backup of the update of the addon, unless i revert the whole system back a cannot restore to the previous configuration.

I cannot find anything that could help me resolve this issue.

Can you help me resolve this issue?

### Are you using the latest released version?

- [x] Yes

### Have you read the troubleshooting page?

- [x] Yes

### What type of installation are you running?

Home Assistant Signal Addon

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

arm64

**Comment by Skons** [comment]
My accounts.json looks like this
``` json
{
  "accounts" : [ {
    "path" : "372758",
    "environment" : "LIVE",
    "number" : "[redacted]",
    "uuid" : "[redacted]"
  } ],
  "version" : 2
}
```

The file 372758 exists

**Comment by bbernhard** [comment]
Do you get the same error in normal mode?

**Comment by Skons** [comment]
No, but when i try to send a message i get this error `Failed to perform the action notify.signal. Unknown error`. This is what the addon reports
```
[GIN] 2025/07/05 - 12:05:27 | 400 |  566.788801ms |    [redacted] | POST     "/v2/send"
[GIN] 2025/07/05 - 12:06:14 | 200 |      85.713µs |     [redacted] | GET      "/v1/about"
[GIN] 2025/07/05 - 12:06:15 | 400 |  947.045568ms |     [redacted] | POST     "/v2/send"
[GIN] 2025/07/05 - 12:06:15 | 400 |  947.045568ms |     [redacted] | POST     "/v2/send"
```

**Comment by bbernhard** [comment]
For testing purposes, please try to send a message via `curl`. What error do you get there?

**Comment by Skons** [comment]
```
 curl -X POST -H "Content-Type: application/json" 'http://[redacted]/v2/send' \
 -d '{"message": "Test via Signal API!", "number": "[redacted]", "recipients": [ "[redacted]" ]}'

{"error":"Error: Unable to initialize main class org.asamk.signal.Main\nCaused by: java.lang.NoClassDefFoundError: org/bouncycastle/jcajce/provider/config/ConfigurableProvider\n"}
```

**Comment by bbernhard** [comment]
That's a really weird error. I do have a test version here which builds against the latest signal-cli version. Would be interesting to know if you still see the same error there. But since you are using the HA addon, it's probably not so easy to test for you (I am not that familiar with the HA addon, but I _think_ you can't just reference a normal docker image there, right?)

**Comment by Skons** [comment]
I doubt if that is necessary.

First: i do not want to do custom dockers into HA, because that docker instance is managed i do not want to mingle with an unmanaged docker container, though this is very good possible (portainer is available).

Second: i had in mind to spin up an instance in my own docker instance, and tonight i got time for that. I copied the config data from my HA addon to that docker container, and BAM, it worked. So i think that my addon is broke. I will reinstall that addon and come back with the results.

<img width="1102" height="140" alt="Image" src="https://github.com/user-attachments/assets/218e10a5-86cf-425c-8986-5cd361a915f3" />

**Comment by Skons** [comment]
After reinstalling, i got this message with curl
``` json
{"error":"Error: A JNI error has occurred, please check your installation and try again\nException in thread \"main\" java.lang.ExceptionInInitializerError\n\tat java.base/sun.launcher.LauncherHelper.getLocalizedMessage(LauncherHelper.java:503)\n\tat java.base/sun.launcher.LauncherHelper.abort(LauncherHelper.java:667)\n\tat java.base/sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:899)\n\tat java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:726)\nCaused by: java.util.MissingResourceException: Can't find bundle for base name sun.launcher.resources.launcher, locale en_US\n\tat java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2059)\n\tat java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1697)\n\tat java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1589)\n\tat java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1555)\n\tat java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:861)\n\tat java.base/sun.launcher.LauncherHelper$ResourceBundleHolder.\u003cclinit\u003e(LauncherHelper.java:129)\n\t... 4 more\nCaused by: java.lang.ExceptionInInitializerError\n\tat java.base/java.security.AccessControlContext.\u003cinit\u003e(AccessControlContext.java:270)\n\tat java.base/java.security.AccessController.createWrapper(AccessController.java:649)\n\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:461)\n\tat java.base/java.util.ResourceBundle$ResourceBundleProviderHelper.loadResourceBundle(ResourceBundle.java:3628)\n\tat java.base/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1851)\n\tat java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1782)\n\tat java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1736)\n\tat java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1736)\n\tat java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1670)\n\t... 8 more\nCaused by: java.lang.RuntimeException: Invalid jdk.io.permissionsUseCanonicalPath: false\n\tat java.base/sun.security.util.FilePermCompat.\u003cclinit\u003e(FilePermCompat.java:58)\n\t... 17 more\n"}
```
My workaround for now is that i am running signal in my docker.

**Comment by bbernhard** [comment]
> After reinstalling, i got this message with curl
> 
> {"error":"Error: A JNI error has occurred, please check your installation and try again\nException in thread \"main\" java.lang.ExceptionInInitializerError\n\tat java.base/sun.launcher.LauncherHelper.getLocalizedMessage(LauncherHelper.java:503)\n\tat java.base/sun.launcher.LauncherHelper.abort(LauncherHelper.java:667)\n\tat java.base/sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:899)\n\tat java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:726)\nCaused by: java.util.MissingResourceException: Can't find bundle for base name sun.launcher.resources.launcher, locale en_US\n\tat java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2059)\n\tat java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1697)\n\tat java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1589)\n\tat java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1555)\n\tat java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:861)\n\tat java.base/sun.launcher.LauncherHelper$ResourceBundleHolder.\u003cclinit\u003e(LauncherHelper.java:129)\n\t... 4 more\nCaused by: java.lang.ExceptionInInitializerError\n\tat java.base/java.security.AccessControlContext.\u003cinit\u003e(AccessControlContext.java:270)\n\tat java.base/java.security.AccessController.createWrapper(AccessController.java:649)\n\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:461)\n\tat java.base/java.util.ResourceBundle$ResourceBundleProviderHelper.loadResourceBundle(ResourceBundle.java:3628)\n\tat java.base/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1851)\n\tat java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1782)\n\tat java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1736)\n\tat java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1736)\n\tat java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1670)\n\t... 8 more\nCaused by: java.lang.RuntimeException: Invalid jdk.io.permissionsUseCanonicalPath: false\n\tat java.base/sun.security.util.FilePermCompat.\u003cclinit\u003e(FilePermCompat.java:58)\n\t... 17 more\n"}
> 
> My workaround for now is that i am running signal in my docker.

So, it works with the docker image but not with the HA addon?

**Comment by Skons** [comment]
That is correct

**Comment by Skons** [comment]
Solved with the latest Home Assistant addon

**Comment by Ascendor** [comment]
I had the same issue today. Fwiw: It was solved after restarting the HA add-on. I hope it doesn't come up on a regular basis.

**Comment by elgatho** [comment]
the same here, is there any possibility to add this to healthcheck? Reboot did the trick.

**Comment by shunopoli** [comment]
I am having this same issue.  Restarting the add-on fixes the issue. Not sure what else to try. I even tried to enter my number for the username ( suggestion from other posts), but that didn't resolve the issue
